name: Build & Push backend image to ECR

on:
  push:
    branches: [main]           # adapt if you use a different default branch
    paths:
      - "api/**"
      - "ml/**"
      - "models/**"
      - ".github/workflows/push-ecr.yml"
  workflow_dispatch:           # manual trigger

env:
  AWS_REGION: eu-central-1
  IMAGE_NAME: 726580147864.dkr.ecr.eu-central-1.amazonaws.com/where-backend-openai

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read           # only code checkout required

    steps:
    - name: Checkout repository (incl. LFS)
      uses: actions/checkout@v4
      with:
        lfs: true

    # ---- OPTIONAL: quick integrity check – keep or drop as you like ----
    - name: Verify model artefacts are present
      run: |
        echo "listing models/ …"
        ls -lh models/
        echo "listing .dockerignore …"
        cat .dockerignore || true
    # -------------------------------------------------------------------

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build & push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file:    ./api/docker/Dockerfile.gpu
        push:    true
        build-args: |
          CACHEBUST=${{ github.sha }}   # <- forces Poetry layer rebuild
        tags: |
          ${{ env.IMAGE_NAME }}:${{ github.sha }}
          ${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha
        cache-to:   type=gha,mode=max

    - name: Show resulting image digest
      run: echo "Pushed ${{ env.IMAGE_NAME }}:${{ github.sha }} and :latest"
